# Generated by Django 3.0 on 2020-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=2083)),
                ('videoTime', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=2083)),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('views', models.FloatField()),
                ('uploadeDay', models.FloatField()),
            ],
        ),
    ]
