# Generated by Django 3.0 on 2020-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_userprofile_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(max_length=2083, upload_to=''),
        ),
    ]
