# Generated by Django 3.0 on 2020-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200927_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(default='images/default_icon.png', upload_to=''),
        ),
    ]
